//hosting seria jogar o valor aderido mesmo que depois de chamar a variável para ela...
//exemplo...
console.log("a = ", a) /*o valor de "a" será "undefined", ou seja, não definido, 
porém mesmo assim a criação da variável "a" foi aceita, o programa sabe da existência da
variável mesmo que definida depois da chamada dela..*/
var a = 2 
console.log("a =", a)
//OBS: Isto só acontece com variáveis do tipo VAR, do tipo LET não daria certo...